language: node_js
node_js:
  - "8.0.0"
  - "8.2.1"  
  - "9.2.1"

branches:
  only:
    - master
    - dev

before_install:
  - sudo apt-get install -y tshark sox

before_script:
  - npm run lint

after_success:
  - npm run coverage